before_cache: 
  - "rm -rf $HOME/.m2/repository/org/ligoj"
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
before_install: 
  - "chmod +x ./travis.sh"
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/maven
install: /bin/true 
jdk: oraclejdk9
matrix:
  include:
      - env: JDK='OpenJDK 10'
        install: . ./install-jdk.sh -F 10 -L GPL
language: java
notifications: 
  email: false
script: "./travis.sh"
sudo: false
