before_cache: 
  - "rm -rf $HOME/.m2/repository/org/ligoj"
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
before_install: 
  - "chmod +x ./travis.sh"
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/maven
install: /bin/true 
jdk: oraclejdk9
language: java
notifications: 
  email: false
script: "./travis.sh"
sudo: false
