version: 2
jobs:
  build:
    working_directory: ~/circleci-feature9
    docker:
      - image: maven:3.6.3-jdk-13
    steps:
      - checkout
      - restore_cache:
          key: circleci-feature9-{{ checksum "pom.xml" }}
      - run:
          command: |
            mvn install -DskipITs=true
          when: always
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-feature9-{{ checksum "pom.xml" }}
